services:
  spark-master:
    image: bitnami/spark:latest
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8080:8080"
    networks:
      - spark-network

  jupyter:
    build: .
    ports:
      - "8888:8888"
    networks:
      - spark-network
    volumes:
      - ./local_lake:/home/jovyan/local_lake
      - ./notebooks:/home/jovyan/
    depends_on:
      - spark-master
    environment:
      # - GRANT_SUDO=yes
      - PYSPARK_SUBMIT_ARGS=--packages org.elasticsearch:elasticsearch-spark-30_2.12:8.15.1,io.delta:delta-core_2.12:2.4.0 pyspark-shell
    user: root
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1  # specify version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # adjust as per your needs
      - xpack.security.enabled=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - myvol:/usr/share/elasticsearch/data
    networks:
      - spark-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1  # specify version
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false 
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - spark-network

networks:
  spark-network:
volumes:
  myvol: